services:
  agendador-tarefas:
    build:
      context: ../agendador_de_tarefas
      dockerfile: Dockerfile
    container_name: agendador-tarefas
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/db_agendador
    depends_on:
      - mongo
    networks:
      - app-network

  bff-agendador-tarefas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bff-agendador-tarefas
    ports:
      - "8083:8083"
    environment:
      - USUARIO_URL=http://usuario:8080/usuario
      - AGENDADOR_TAREFAS_URL=http://agendador-tarefas:8081/tarefas
      - NOTIFICACAO_URL=http://notificacao:8082/email
    depends_on:
      - usuario
      - agendador-tarefas
      - notificacao
    networks:
      - app-network

  usuario:
    build:
      context: ../usuario
      dockerfile: Dockerfile
    container_name: usuario
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db_usuario
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres
    networks:
      - app-network

  notificacao:
    build:
      context: ../notificacao
      dockerfile: Dockerfile
    container_name: notificacao
    ports:
      - "8084:8084"
    depends_on:
      - mongo
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_usuario
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mongo:
    image: mongo:6-jammy
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db_agendador
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  postgres_data:
  mongo_data:

networks:
  app-network:
    driver: bridge